DROP TABLE IF EXISTS ORDER_BY_TABLE;

CREATE TABLE IF NOT EXISTS ORDER_BY_TABLE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM1 INT NOT NULL,
   NUM2 INT NOT NULL
);

CREATE INDEX NUM1_INDEX on ORDER_BY_TABLE(NUM1);

DELETE FROM ORDER_BY_TABLE;

INSERT INTO ORDER_BY_TABLE (NUM1, NUM2)
SELECT (gen.n + 1) / 1000,
(gen.n + 1) % 1000
FROM generator_64k gen;