CREATE TABLE IF NOT EXISTS FILTERED_TABLE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM1 INT NOT NULL,
   NUM2 INT NOT NULL,
   COL INT NOT NULL
);

CREATE INDEX NUM1 on FILTERED_TABLE(NUM1);

DELETE FROM FILTERED_TABLE;

INSERT INTO FILTERED_TABLE(NUM1, NUM2, COL) VALUES(1, 1, 1);
INSERT INTO FILTERED_TABLE(NUM1, NUM2, COL) VALUES(1, 2, 1);
INSERT INTO FILTERED_TABLE(NUM1, NUM2, COL) VALUES(2, 1, 1);
INSERT INTO FILTERED_TABLE(NUM1, NUM2, COL) VALUES(2, 2, 1);

