CREATE TABLE IF NOT EXISTS RANGE_TABLE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM1 INT NOT NULL,
   NUM2 INT NOT NULL
);

CREATE INDEX RANGE_TABLE_INDEX on RANGE_TABLE(NUM1);

DELETE FROM RANGE_TABLE;

INSERT INTO RANGE_TABLE (NUM1, NUM2)
SELECT gen.n + 1,
gen.n + 1
FROM generator_64k gen;