version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - mysql-network
    container_name: "mysql"
    volumes:
      - test_index_db_data:/var/lib/mysql


  cli:
    image: mysql:8.0.27
    networks:
      - mysql-network
    command: mysql -hmysql -uuser -ppassword db

networks:
  mysql-network:
    driver: bridge

volumes:
  test_index_db_data: