CREATE TABLE IF NOT EXISTS COVERING_INDEX (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM1 INT NOT NULL,
   NUM2 INT NOT NULL
);

CREATE INDEX NOT_UNIQUE_KEY_INDEX on COVERING_INDEX(NUM1, NUM2);

DELETE FROM COVERING_INDEX;

INSERT INTO COVERING_INDEX (NUM1, NUM2)
SELECT gen.n + 1,
gen.n + 1
FROM generator_64k gen;
