CREATE TABLE IF NOT EXISTS INDEX_NO_INDEX_TABLE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM1 INT NOT NULL,
   NUM2 INT NOT NULL
);

DELETE FROM INDEX_NO_INDEX_TABLE;

INSERT INTO INDEX_NO_INDEX_TABLE (NUM1, NUM2)
SELECT (gen.n + 1) % 1000,
gen.n + 1
FROM generator_64k gen;

CREATE INDEX ONLY_NUM1_INDEX on INDEX_NO_INDEX_TABLE(NUM1);
