CREATE TABLE IF NOT EXISTS NOT_UNIQUE_KEY_TABLE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM INT NOT NULL
);

CREATE INDEX NOT_UNIQUE_KEY_INDEX on NOT_UNIQUE_KEY_TABLE(NUM);

DELETE FROM NOT_UNIQUE_KEY_TABLE;

INSERT INTO NOT_UNIQUE_KEY_TABLE (NUM)
SELECT (gen.n + 1) % 10000
FROM generator_64k gen;
