CREATE TABLE IF NOT EXISTS NOT_UNIQUE_KEY_TABLE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM INT NOT NULL,
   COL INT NOT NULL
);

CREATE INDEX NOT_UNIQUE_KEY_INDEX on NOT_UNIQUE_KEY_TABLE(NUM);

DELETE FROM NOT_UNIQUE_KEY_TABLE;

INSERT INTO NOT_UNIQUE_KEY_TABLE (NUM, COL)
SELECT (gen.n + 1) % 10000,
gen.n + 1
FROM generator_64k gen;
