CREATE TABLE IF NOT EXISTS PRIMARY_KEY_TABLE (
   ID INT NOT NULL,
   NUM INT NOT NULL,
   PRIMARY KEY (ID)
);

DELETE FROM PRIMARY_KEY_TABLE;

INSERT INTO PRIMARY_KEY_TABLE (ID, NUM)
SELECT gen.n + 1,
gen.n + 1
FROM generator_64k gen;