EXPLAIN SELECT * FROM MULTI_COLUMN_INDEX_TABLE WHERE NUM1 = 1;
EXPLAIN SELECT * FROM MULTI_COLUMN_INDEX_TABLE WHERE NUM1 = 1 AND NUM2 = 1;
EXPLAIN SELECT * FROM MULTI_COLUMN_INDEX_TABLE WHERE NUM1 = 1 AND NUM2 = 1 AND NUM3 = 1;
EXPLAIN SELECT * FROM MULTI_COLUMN_INDEX_TABLE WHERE NUM2 = 1;
EXPLAIN SELECT * FROM MULTI_COLUMN_INDEX_TABLE WHERE NUM3 = 1;