CREATE TABLE IF NOT EXISTS MULTI_COLUMN_INDEX_TABLE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUM1 INT NOT NULL,
   NUM2 INT NOT NULL,
   NUM3 INT NOT NULL
);

CREATE INDEX MULTI_COLUMN_INDEX on MULTI_COLUMN_INDEX_TABLE(NUM1, NUM2, NUM3);

DELETE FROM MULTI_COLUMN_INDEX_TABLE;

INSERT INTO MULTI_COLUMN_INDEX_TABLE (NUM1, NUM2, NUM3)
SELECT gen.n + 1,
gen.n + 2,
gen.n + 3
FROM generator_64k gen;
